logging:
  lever:
    com.rabbitmq.mqtt: INFO
spring:
  profiles:
    active: dev
---
spring:
  profile: dev
  mqtt:
    url: tcp://127.0.0.1:1883
    username: guest
    password: guest
    client_id: mqttId1
    default.topic: test
    qos: 1
    timeOut: 10000
    keepAlive: 20
mqtt.run.mode: demo
---
spring:
  profile: uat
  mqtt:
    host.url: tcp://127.0.0.1:1883
    username: guest
    password: guest
    client_id: mqttId1
    default.topic: test
    qos: 1
    timeOut: 10000
    keepAlive: 20
---
spring:
  profile: prod
  mqtt:
    url: tcp://127.0.0.1:1883
    username: guest
    password: guest
    client_id: mqttId1
    default.topic: test
    qos: 1
    timeOut: 10000
    keepAlive: 20
